apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ .Release.Name }}-obc
  labels:
    {{- include "object-bucket-backup.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  generateBucketName: {{ .Release.Name }}
  storageClassName: {{ .Values.target.obcStorageClassName }}
